import { describe, it, expect } from "vitest";
import { render, screen, fireEvent, within } from "@testing-library/react";
import { DataTable } from "../DataTable";
import { Order } from "@/lib/mockData";

const mockData: Order[] = [
  {
    id: "ORD-001",
    customerName: "Alpha Roasters",
    roastType: "Light Roast",
    quantity: 50,
    totalAmount: 500,
    status: "Pending",
    date: "2023-10-01",
  },
  {
    id: "ORD-002",
    customerName: "Beta Coffee",
    roastType: "Dark Roast",
    quantity: 100,
    totalAmount: 950,
    status: "Shipped",
    date: "2023-10-02",
  },
  {
    id: "ORD-003",
    customerName: "Gamma Beans",
    roastType: "Medium Roast",
    quantity: 25,
    totalAmount: 260,
    status: "Delivered",
    date: "2023-10-03",
  },
];

describe("DataTable Component", () => {
  it("should render the correct number of rows", () => {
    render(<DataTable data={mockData} />);

    // 1 header row + 3 data rows
    const rows = screen.getAllByRole("row");
    expect(rows).toHaveLength(4);

    expect(screen.getByText("Alpha Roasters")).toBeInTheDocument();
    expect(screen.getByText("Beta Coffee")).toBeInTheDocument();
    expect(screen.getByText("Gamma Beans")).toBeInTheDocument();
  });

  it("should filter rows based on global search input", () => {
    render(<DataTable data={mockData} />);

    const searchInput = screen.getByPlaceholderText("Search orders...");

    // Type 'Alpha' into search
    fireEvent.change(searchInput, { target: { value: "Alpha" } });

    // Header + 1 matched row
    expect(screen.getAllByRole("row")).toHaveLength(2);
    expect(screen.getByText("Alpha Roasters")).toBeInTheDocument();
    expect(screen.queryByText("Beta Coffee")).not.toBeInTheDocument();
  });

  it("should sort rows when clicking on column headers", () => {
    render(<DataTable data={mockData} />);

    // 'Customer' is the header text generated by TanStack Table for 'customerName' accessor
    const customerHeader = screen.getByText("Customer");

    // First click: Sort ASC (Alpha, Beta, Gamma)
    fireEvent.click(customerHeader);
    let rows = screen.getAllByRole("row");
    expect(within(rows[1]).getByText("Alpha Roasters")).toBeInTheDocument();
    expect(within(rows[3]).getByText("Gamma Beans")).toBeInTheDocument();

    // Second click: Sort DESC (Gamma, Beta, Alpha)
    fireEvent.click(customerHeader);
    rows = screen.getAllByRole("row");
    expect(within(rows[1]).getByText("Gamma Beans")).toBeInTheDocument();
    expect(within(rows[3]).getByText("Alpha Roasters")).toBeInTheDocument();
  });
});
